package de.timoklostermann.refuel.datastore.enums;

public enum ConsumptionUnits {
	MILES_PER_GALLON,
	KILOMETERS_PER_GALLON,
	MILES_PER_IMPERIAL_GALLON,
	KILOMETERS_PER_IMPERIAL_GALLON,
	MILES_PER_LITER,
	KILOMETERS_PER_LITER,
	GALLONS_PER_100_KILOMETERS,
	LITER_PER_100_KILOMETERS,
	IMPERIAL_GALLONS_PER_100_KILOMETERS
}
